### ISSUE TITLE
Stuck on Please try to reconnect in a minute on minecraft

### ISSUE THREAD

**Issue by eyes-eyes** [joesturge/lazymc-docker-proxy#115]
Hello itzg directed me to come here for support.
I am using a ubuntu server and trying to use lazymc proxy. I coped the example configuration from the readme and added my mc environment variables on top of it. Only the lazymc-proxy container is running but still can't connect to the server. 
When I log the lazymc-proxy container it keeps saying this:

> ERROR mc::lazymc::monitor             > Force killing server, took too long to start or stop
> ERROR lazymc-docker-proxy::health     > Application is unhealthy.
> WARN  mc::lazymc                      > Failed to force kill server

When I try to join from minecraft just keeps saying "Server is starting ... try to reconnect in a minute"

**Comment by joesturge** [comment]
Could you send me the docker compose your are using?

**Comment by joesturge** [comment]
I think I know the issue, there is a start timeout setting which defaults to 300secs which has not been mapped in the configuration class here, could you start your forge server without using lazymc and tell me how many seconds it takes to start the server? If it's more than 300secs then this is the problem

**Comment by eyes-eyes** [comment]
I'm busy this week. I'll let you know in 6 days.

**Comment by eyes-eyes** [comment]
I'm using fabric type server from itzg image and this is the output when logging mc container:
[Server thread/INFO]: Done (10.545s)! For help, type "help"
Dedicated server took 38.318 seconds to load

**Comment by joesturge** [comment]
you need version 2.6.1

**Comment by straboti** [comment]
Hi! I'm facing a similar issue with a Paper server...

> [21:48:19 INFO]: Done (17.965s)! For help, type "help"
[21:48:19 INFO]: [ServerBackup] ServerBackup: No updates found. The server is running the latest version.
[21:48:19 INFO]: [Plan] You're using the latest version.
lazymc              |  WARN  mc::lazymc                       > Held client reached timeout of 25s
lazymc              |  ERROR mc::lazymc::monitor              > Force killing server, took too long to start or stop
lazymc              |  WARN  mc::lazymc                       > Server process stopped with error code (signal: 9 (SIGKILL))
lazymc              |  ERROR mc::lazymc::monitor              > Force killing server, took too long to start or stop
lazymc              |  WARN  mc::lazymc                       > Failed to force kill server
lazymc              |  INFO  mc::lazymc::monitor              > Server is now sleeping
lazymc              |  ERROR mc::lazymc                       > Server stopped for held client, disconnecting
lazymc              |  WARN  mc::lazymc                       > Server stopping for held client
lazymc              |  INFO  mc::lazymc                       > Starting server for 'StraboCraft'...
lazymc              |  INFO  mc::lazymc-docker-proxy::command > Received command to start group: mc
lazymc              |  WARN  mc::lazymc                       > Held client reached timeout of 25s

I tried it with different timeouts, but still the same. Maybe it is not detecting the server start-stops correctly when using Paper?

Docker-compose.yml:

```yml
networks:
  minecraft-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  lazymc:
    container_name: lazymc
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    environment:
      # Point to the service name of the Minecraft server
      SERVER_ADDRESS: survival:25565
      # Required to find the container to manage it
      LAZYMC_GROUP: mc
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.2
    restart: unless-stopped
    volumes:
          # you should mount the minecraft server dir under /server, using read only.
      - ./survival-data:/server:ro
      # you need to supply the docker socket, so that the container can run docker command
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # lazymc-docker-proxy acts as a proxy, so there is
      # no need to expose the server port on the Minecraft container
      - "25565:25565"
  survival:
    image: itzg/minecraft-server
    container_name: minecraft-survival
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.3
    labels:
      - lazymc.enabled=true
      - lazymc.group=mc
      - lazymc.server.address=mc:25565
      - lazymc.server.start_timeout=40
    ports:
      - 8804:8804
    environment:
      EULA: "TRUE"
      INIT_MEMORY: 2G
      MAX_MEMORY: 5G
      TYPE: "PAPER"
      TZ: "Europe/Budapest"
    volumes:
      - ./survival-data:/data  # Bind local directory to container's data folder
    tty: true
    stdin_open: true
    restart: no
```
