### ISSUE TITLE
Show server icon

### ISSUE THREAD

**Issue by brunobeeee** [joesturge/lazymc-docker-proxy#123]
Maybe I'm missing sth but for me lazymc is not showing the `server-icon.png` from the actual mc server although I have mounted the server data dir correctly.

```yaml
services:
  lazymc:
    volumes:
      - ./data:/server:ro
  
  mc:
    volumes:
       - ./data:/data
```

Is this a bug or is it just now intended to work like this?
