### ISSUE TITLE
Lazymc Docker Proxy doesnt allow me to connect to the Minecraft Game Server

### ISSUE THREAD

**Issue by FurkanVG** [joesturge/lazymc-docker-proxy#134]
Hi,

i am trying to combine this docker image with my itzg minecraft container.

The docker compose:

```
networks:
  minecraft-network:
    driver: bridge    
    ipam:
      config:
        - subnet: 172.58.0.0/16

services:
  lazymc:
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    # the IPs should start at .2 as .1 is reserved for the gateway
    networks:
      minecraft-network:
        ipv4_address: 172.58.0.2
    restart: unless-stopped
    volumes:
      # you should mount the minecraft server dir under /server, using read only.
      - Minecraft-Data:/server:ro
      # you need to supply the docker socket, so that the container can run docker command
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # lazymc-docker-proxy acts as a proxy, so there is
      # no need to expose the server port on the Minecraft container
      - "49152:25565"

  mc:
    image: itzg/minecraft-server
    networks:
      minecraft-network:
        ipv4_address: 172.58.0.3
    labels:
      # Set lazymc.enabled to true to enable lazymc on this container
      - lazymc.enabled=true
      - lazymc.server.start_timeout=500
      # Required to find the container to manage it
      - lazymc.group=mc
      # Point to the service name of the Minecraft server
      - lazymc.server.address=mc:25565
      - "com.centurylinklabs.watchtower.enable=false" # Exclude from Watchtower
    container_name: minecraft-skyfam
    hostname: minecraft-skyfam
    tty: true
    stdin_open: true
    ports:
      # - "49152:25565"
      - "25575:25575"
      - "8100:8100"
      - "8804:8804"
    restart: unless-stopped

    environment:
      VIEW_DISTANCE: "10"
      OVERRIDE_WHITELIST: "true"
      WHITELIST: |
        user
    volumes:
      - Minecraft-Data:/data
      - Minecraft-Mods:/mods
      - Minecraft-Plugins:/plugins

volumes:
  Minecraft-Data:
    external: true
  Minecraft-Mods:
    external: true
  Minecraft-Plugins:
    external: true
  Minecraft-Backups:
    external: true
```
i removes some ENV variables not related to this, so as fyi.

The current scenario:

1. The initial start of the docker compose looks fine. I see that the lazy mc docker proxy is starting fine, and that the main mc server is offline. I als see the MOTD
2. When i try to connect then to the MC Server, it sees the connection and it starts then the mc docker container, all good. Few minutes later the mc docker container is online, BUT I can not connect to it. Even tho the mc docker container is running, it just is stuck at "Connecting to the server". The logs of lazy mc show this:
![image](https://github.com/user-attachments/assets/64f9379f-7e28-4c56-8556-083e995d706b)

Now i had thought it would be related to how long my mc server takes time to boot up, so i increased the timeout to 500s, but that didnt help. I dont know where the issue is? Is it the port changing i did? I have adapted this in the compose and it shouldnt be an issue.
