### ISSUE TITLE
Containers exit with "Application is unhealthy"

### ISSUE THREAD

**Issue by DemonChicken1111** [joesturge/lazymc-docker-proxy#182]
## The Issue

I am using lazymc in conjunction with mc-router as I would like to run multiple servers on the same host. I am however running into an issue where everything seems to work and start to setup but then all of my containers exit on `lazymc-docker-proxy::health > application is unhealthy` I am not sure why it is giving me this error code. There is nothing that I see wrong with my compose file, and I'm not getting much out of the log output that I understand. 

 ## docker-compose.yml:
```yaml
networks:
  minecraft-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16

services:
  router:
    # mc-router routes external traffic to servers via lazymc
    image: itzg/mc-router
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.2
    environment:
      MAPPING: |
        services.hardware-marauding.space=lazymc:25565
        private.hardware-marauding.space=lazymc:25566
    ports:
      - "25565:25565"

  lazymc:
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.3
    restart: unless-stopped
    environment:
      RUST_LOG: "debug"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # primary server vol. mount, matches the label
      - data:/server/mc:ro
      # secondary server vol. mount, matches the label
      - data-mc2:/server/mc2:ro
    depends_on:
      - router

  mc:
    image: itzg/minecraft-server:java21
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.4
    labels:
      - lazymc.enabled=true
      - lazymc.group=mc
      - lazymc.server.address=services:25565
      - lazymc.port=25565
      - lazymc.server.directory=/server/mc
    tty: true
    stdin_open: true
    restart: no
    environment:
      EULA: TRUE
      VERSION: 1.21.4
      MODE: 0
      RCON_PASSWORD: password
      TYPE: PAPER
      MEMORY: 6G
      SPIGET_RESOURCES: 18494
    volumes:
      - ./data:/data

  mc2:
    image: itzg/minecraft-server:java21
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.5
    labels:
      - lazymc.enabled=true
      - lazy.group=mc2
      - lazymc.server.address=private:25566
      - lazymc.port=25566
      - lazymc.server.directory=/server/mc2
    tty: true
    stdin_open: true
    restart: no
    environment:
      EULA: "TRUE"
      VERSION: 1.21.4
      MODE: 0
      RCON_PASSWORD: password
      TYPE: PAPER
      MEMORY: 4G
    volumes:
      - ./data-mc2:/data
  
volumes:
  data:
  data-mc2:
```

## error example (I can provide more if needed):
```
lazymc-1  | 
lazymc-1  |  DEBUG lazymc-docker-proxy::docker     > Found 2 container(s) to get labels
lazymc-1  |  DEBUG lazymc-docker-proxy::docker     > Resolved address: 172.18.0.5:25566
lazymc-1  |  DEBUG lazymc-docker-proxy::docker     > Resolved address: 172.18.0.4:25565
lazymc-1  |  ERROR lazymc-docker-proxy::entrypoint::config > lazymc.group is not set
mc2-1     | Applying patches
mc2-1     | Starting org.bukkit.craftbukkit.Main
mc2-1     | *** Warning, you've not updated in a while! ***
lazymc-1  |  DEBUG lazymc-docker-proxy::health             > Setting health status to: UNHEALTHY
lazymc-1  |  ERROR lazymc-docker-proxy::health             > Application is unhealthy.
lazymc-1  |  INFO  lazymc-docker-proxy::entrypoint > Ensuring all server containers are stopped...
lazymc-1  |  DEBUG bollard::docker                 > unix://2f7661722f72756e2f646f636b65722e736f636b/containers/json?all=true&size=false&filters=%7B%22label%22%3A%5B%22lazymc.enabled%3Dtrue%22%5D%7D
lazymc-1  |  DEBUG bollard::docker                 > Decoded into string: [{"Id":"0d6f927e5d53765f209c091da029765bf3bb770fbcfcd121885aab941f1c08a2","Names":["/mineserver-mc2-1"],"Image":"itzg/minecraft-server:java21","ImageID":"sha256:bef47a89663d85739126cfdba3c8a0c35cc5171745204d1a66059f38932bd863","Command":"/start","Created":1738817841,"Ports":[],"Labels":{"com.docker.compose.config-hash":"256fee3698eddebdc3e50e2a408d36beaa0c94d82bb69a562ff6b4888c3fd6c8","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:bef47a89663d85739126cfdba3c8a0c35cc5171745204d1a66059f38932bd863","com.docker.compose.oneoff":"False","com.docker.compose.project":"mineserver","com.docker.compose.project.config_files":"/home/gaming/MineServer/docker-compose.yml","com.docker.compose.project.working_dir":"/home/gaming/MineServer","com.docker.compose.service":"mc2","com.docker.compose.version":"2.32.4","lazy.group":"mc2","lazymc.enabled":"true","lazymc.port":"25566","lazymc.server.address":"private:25566","lazymc.server.directory":"/server/mc2","org.opencontainers.image.authors":"Geoff Bourne <itzgeoff@gmail.com>","org.opencontainers.image.created":"2025-02-02T23:50:31.460Z","org.opencontainers.image.description":"Docker image that provides a Minecraft Server for Java Edition that automatically downloads selected version at startup","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.ref.name":"ubuntu","org.opencontainers.image.revision":"1fb7e50c0dcfd8dfd786a91fae864d38d2029a1f","org.opencontainers.image.source":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.title":"docker-minecraft-server","org.opencontainers.image.url":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.version":"java21"},"State":"exited","Status":"Exited (137) 11 seconds ago","HostConfig":{"NetworkMode":"mineserver_minecraft-network"},"NetworkSettings":{"Networks":{"mineserver_minecraft-network":{"IPAMConfig":{"IPv4Address":"172.18.0.5"},"Links":null,"Aliases":null,"MacAddress":"","DriverOpts":null,"NetworkID":"5450f4a1c3c377ce2ed33788d02f882dce1d4296b2ca986bc60feb5fab05d2cf","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"DNSNames":null}}},"Mounts":[{"Type":"volume","Name":"mineserver_data-mc2","Source":"/var/lib/docker/volumes/mineserver_data-mc2/_data","Destination":"/data","Driver":"local","Mode":"z","RW":true,"Propagation":""}]},{"Id":"bce1e16b2d4ed8c53435dc724812e9bc2fe07869d57ec2707a4b25bc1d32be1f","Names":["/mineserver-mc-1"],"Image":"itzg/minecraft-server:java21","ImageID":"sha256:bef47a89663d85739126cfdba3c8a0c35cc5171745204d1a66059f38932bd863","Command":"/start","Created":1738817841,"Ports":[],"Labels":{"com.docker.compose.config-hash":"78dbafb17d7cb74eeca3f88953e52ccae7ed2bb91a7759c0bfb27a6124175a72","com.docker.compose.container-number":"1","com.docker.compose.depends_on":"","com.docker.compose.image":"sha256:bef47a89663d85739126cfdba3c8a0c35cc5171745204d1a66059f38932bd863","com.docker.compose.oneoff":"False","com.docker.compose.project":"mineserver","com.docker.compose.project.config_files":"/home/gaming/MineServer/docker-compose.yml","com.docker.compose.project.working_dir":"/home/gaming/MineServer","com.docker.compose.service":"mc","com.docker.compose.version":"2.32.4","lazymc.enabled":"true","lazymc.group":"mc","lazymc.port":"25565","lazymc.server.address":"services:25565","lazymc.server.directory":"/server/mc","org.opencontainers.image.authors":"Geoff Bourne <itzgeoff@gmail.com>","org.opencontainers.image.created":"2025-02-02T23:50:31.460Z","org.opencontainers.image.description":"Docker image that provides a Minecraft Server for Java Edition that automatically downloads selected version at startup","org.opencontainers.image.licenses":"Apache-2.0","org.opencontainers.image.ref.name":"ubuntu","org.opencontainers.image.revision":"1fb7e50c0dcfd8dfd786a91fae864d38d2029a1f","org.opencontainers.image.source":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.title":"docker-minecraft-server","org.opencontainers.image.url":"https://github.com/itzg/docker-minecraft-server","org.opencontainers.image.version":"java21"},"State":"exited","Status":"Exited (137) Less than a second ago","HostConfig":{"NetworkMode":"mineserver_minecraft-network"},"NetworkSettings":{"Networks":{"mineserver_minecraft-network":{"IPAMConfig":{"IPv4Address":"172.18.0.4"},"Links":null,"Aliases":null,"MacAddress":"","DriverOpts":null,"NetworkID":"5450f4a1c3c377ce2ed33788d02f882dce1d4296b2ca986bc60feb5fab05d2cf","EndpointID":"","Gateway":"","IPAddress":"","IPPrefixLen":0,"IPv6Gateway":"","GlobalIPv6Address":"","GlobalIPv6PrefixLen":0,"DNSNames":null}}},"Mounts":[{"Type":"volume","Name":"mineserver_data","Source":"/var/lib/docker/volumes/mineserver_data/_data","Destination":"/data","Driver":"local","Mode":"z","RW":true,"Propagation":""}]}]
```

```
mc2-1     | 2025-02-06T05:02:43.446Z	INFO	mc-server-runner	gracefully stopping server...
mc2-1     | 2025/02/06 05:02:43 Stopping with rcon-cli
mc2-1     | 2025-02-06T05:02:43.455Z	ERROR	mc-server-runner	Failed to stop using rcon-cli	{"error": "exit status 1"}
mc2-1     | 2025-02-06T05:02:43.456Z	INFO	mc-server-runner	Sending 'stop' to Minecraft server...
mc2-1     | stop
lazymc-1  |  DEBUG lazymc-docker-proxy::docker     > Resolved address: 172.18.0.4:25565
lazymc-1  |  ERROR lazymc-docker-proxy::entrypoint::config > lazymc.group is not set
lazymc-1  |  DEBUG lazymc-docker-proxy::health             > Setting health status to: UNHEALTHY
lazymc-1  |  ERROR lazymc-docker-proxy::health             > Application is unhealthy.
lazymc-1  |  INFO  lazymc-docker-proxy::entrypoint > Ensuring all server containers are stopped...
```

[log.txt](https://github.com/user-attachments/files/18683611/log.txt)

**Comment by joesturge** [comment]
Hi, I think your volumes on your mc and mc2 containers are specified wrong:

```
volumes:
      - ./data:/data
```

should be

```
volumes:
      - data:/data
```

and the same for `./data/mc2`

See if this fixes your issue

**Comment by DemonChicken1111** [comment]
I did try that, I have a current server which lives in the directory at /data and I would like to migrate that over. I originally used lazytainer for this. I will try it again when I can have some down time and will get back to you asap. I will also include logs with that as well. Thank you for the reply!

**Comment by DemonChicken1111** [comment]
Hi @joesturge, I have changed this in the configuration with no change in error messages or unhealthy status. 

[logs2.txt](https://github.com/user-attachments/files/18813654/logs2.txt)

**Comment by DemonChicken1111** [comment]
I got it working! I messed up the lazymc.group label in mc2. 

However It seems the new config is not getting the world or data of my old server? Is there any reason this could be? I have confirmed that the data is still there, the advancements seem to lineup, all the configs are there, etc. Here is my previous config file:

```yaml
services:
  lazytainer:
    image: ghcr.io/vmorganp/lazytainer:master
    environment:
      VERBOSE: false
    ports:
      - 25565:25565
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - lazytainer.group.minecraft.sleepMethod=stop
      - lazytainer.group.minecraft.ports=25565
      - lazytainer.group.minecraft.minPacketThreshold=2
      - lazytainer.group.minecraft.inactiveTimeout=600
    restart: unless-stopped
    network_mode: bridge

  mc:
    image: itzg/minecraft-server
    environment:
      EULA: TRUE
      VERSION: 1.21.4
      MODE: 0
      RCON_PASSWORD: LazyLlama3060
      TYPE: PAPER
      MEMORY: 6G
      SPIGET_RESOURCES: 18494
    volumes:
      - ./data:/data
    labels:
      - lazytainer.group=minecraft
    depends_on:
      - lazytainer
    network_mode: service:lazytainer
    tty: true
    stdin_open: true
    restart: unless-stopped
```

here is the new log file: [logs3.txt](https://github.com/user-attachments/files/18813721/logs3.txt)
