### ISSUE TITLE
Neoforge server startup not being detected

### ISSUE THREAD

**Issue by elrac** [joesturge/lazymc-docker-proxy#200]
I have a server that I'm running a few fabric servers on through the lazymc proxy and I am attempting to add a neoforge server to it, however the proxy doesn't seem to be detecting that the server has started. I can connect to the server directly through a secondary port while the proxy port is still claiming that the server is starting. Below is the docker compose file. I have tried it with a few other configurations including with the "lazymc.server.directory" and without the port forward. Also, I have tried it without any mods installed in case they were interfering in some way. 

After a period of time I receive the following error in the proxy log. 

```

lazymc-1  |  ERROR mc-create6::lazymc::monitor              > Force killing server, took too long to start or stop
lazymc-1  |  WARN  mc-create6::lazymc                       > Server process stopped with error code (signal: 9 (SIGKILL))
lazymc-1  |  INFO  mc-create6::lazymc::monitor              > Server is now sleeping
```

```
# port 25569
services:
  mc-create6:
    image: itzg/minecraft-server:latest

    labels:
      - lazymc.enabled=true
      - lazymc.group=mc-create6
      - lazymc.server.address=mc-create6:25568
      - lazymc.port=25569
      #- lazymc.server.directory=/server/create6-data
      - lazymc.time.minimum_online_time=180
      - lazymc.server.forge=true
      - lazymc.public.version=1.21.1
      - lazymc.public.protocol=767
    tty: true
    stdin_open: true
    restart: no

    ports:
      - "25580:25569"

    environment:
      EULA: "true"
      VERSION: 1.21.1
      SERVER_PORT: "25569"
      TYPE: NEOFORGE
      NEOFORGE_VERSION: "21.1.133"
      MODS_FILE: "/extras/mods.txt"
      MEMORY: 6G

    volumes:
      - "../server-data/create6-data:/data"
      - "./timezone:/etc/timezone:ro"
      - "./mods.txt:/extras/mods.txt:ro"

    networks:
      minecraft_network:
        ipv4_address: 172.19.0.7

networks:
  minecraft_network:
    external: true
```
