### ISSUE TITLE
1.7.3 compatibility

### ISSUE THREAD

**Issue by Ahydul** [joesturge/lazymc-docker-proxy#222]
Hello, I'm trying to set up a 1.7.3 modpack called [Better Than Adventure](https://www.betterthanadventure.net/) but I can't manage to make it work. I'm not even sure if this is compatible with 1.7.3 or that mod.

Right now this is my docker compose:

```
# https://github.com/joesturge/lazymc-docker-proxy/tree/master

networks:
  minecraft-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.18.0.0/16
  default:
    name: $DOCKER_MY_NETWORK
    external: true


services:
  minecraft-router:
    image: itzg/mc-router
    container_name: minecraft-router
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.2
    restart: unless-stopped
    depends_on:
      - lazymc
    environment:
      MAPPING: |
        minecraft.$SERVER_HOST=lazymc:24455
        bta.$SERVER_HOST=lazymc:25565
    ports:
      - "24455:25565"

  lazymc:
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    container_name: lazymc
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.3
    restart: unless-stopped
    volumes:
      - ./minecraft_data/main_server:/server/main:ro
      - ./minecraft_data/bta:/server/bta:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    #ports:
    #  - "24455:24455"
    logging:
      options:
        max-size: 10m

  minecraft:
    image: itzg/minecraft-server
    container_name: minecraft
    hostname: minecraft
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.4
    restart: no
    env_file: .env
    tty: true
    stdin_open: true
    volumes:
      - ./minecraft_data/main_server:/data
    labels:
      - lazymc.enabled=true
      - lazymc.group=minecraft
      - lazymc.server.address=minecraft:24455
      - lazymc.port=24455
      - lazymc.server.wake_whitelist=true
      - lazymc.server.directory=/server/main
    ports:
#      - 24455:24455     # minecraft server players connect
      - 8100:8100       # bluemap
      - 9080:9080       # UnifiedMetrics
#      - 8123:8123       # dynmap
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  bta:
    image: itzg/minecraft-server
    container_name: bta
    hostname: bta
    networks:
      minecraft-network:
        ipv4_address: 172.18.0.5
    restart: no
    tty: true
    stdin_open: true
    volumes:
      - ./minecraft_data/bta:/data
    healthcheck:
      disable: true
    environment:
      EULA: true
      TYPE: CUSTOM
      CUSTOM_SERVER: ./bta.v7.3_03.server.jar
      SERVER_HOST: $SERVER_HOST
      SERVER_PORT: 25565
      VERSION: b1.7.3
      MAX_MEMORY: 4G
      ENABLE_ROLLING_LOGS: true
      TZ: $TZ
      DIFFICULTY: hard
      WHITELIST: aaaaa
      EXISTING_WHITELIST_FILE: MERGE
      ENFORCE_WHITELIST: true
      OPS: aaaaa
      ANNOUNCE_PLAYER_ACHIEVEMENTS: true
      SNOOPER_ENABLED: false
      ALLOW_FLIGHT: true
      ALLOW_NETHER: true
    labels:
      - lazymc.enabled=true
      - lazymc.group=bta
      - lazymc.server.address=bta:25565
      - lazymc.port=25565
      - lazymc.server.wake_whitelist=true
      - lazymc.server.directory=/server/bta
    logging:
      driver: "json-file"
      options:
        max-size: "50m"

  # LOG AGENT PUSHING LOGS TO LOKI
  promtail:
    image: grafana/promtail
    container_name: minecraft-promtail
    hostname: minecraft-promtail
    restart: unless-stopped
    volumes:
      - ./minecraft_data/main_server/logs:/var/log/minecraft:ro
      - ./promtail-config.yml:/etc/promtail-config.yml
    command:
      - '-config.file=/etc/promtail-config.yml'
    labels:
      org.label-schema.group: "monitoring"
    logging:
      options:
        max-size: 10m
```

I would appreciate some help. Thanks
