### ISSUE TITLE
Allow to pass in lazymc.toml in volume mount

### ISSUE THREAD

**Issue by joesturge** [joesturge/lazymc-docker-proxy#33]
A use may want to supply a custom `lazymc.toml` to the container

This should come with the releavent documentation and stipulate that they do so at thier own risk etc...

we should support the following:

```yaml
services:
  lazymc:
    container_name: lazymc
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    environment:
      # Point to the service name of the Minecraft server
      SERVER_ADDRESS: mc:25565
      # Required to find the container to manage it
      LAZYMC_GROUP: mc
    restart: unless-stopped
    volumes:
      # you should mount the minecraft server dir under /server, using read only.
      - data:/server:ro
      # you need to supply the docker socket, so that the container can run docker command
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      # lazymc-docker-proxy acts as a proxy, so there is
      # no need to expose the server port on the Minecraft container
      - "25565:25565"
    #    allow users to mount lazymc config to override any values we set
    volumes:
      - ./config:/config
```
