### ISSUE TITLE
proxy to multiple servers like itzg/mc-router

### ISSUE THREAD

**Issue by joesturge** [joesturge/lazymc-docker-proxy#50]
```yaml
services:
  lazymc:
    container_name: lazymc
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    restart: unless-stopped
    volumes:
      - data:/server:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "25565:25565"

  mc1:
    image: itzg/minecraft-server:java21
    container_name: minecraft-server
    labels:
    # By putting the labels on the server you want to proxy to, this could allow for mulitple servers in the future
      - lazymc.group=mc1
      - lazymc.domain=mc1.example.com
      - lazymc.server_address=mc1:25565
    tty: true
    stdin_open: true
    restart: no
    environment:
      EULA: "TRUE"
    volumes:
      - data-mc1:/data

  mc2:
    image: itzg/minecraft-server:java21
    container_name: minecraft-server
    labels:
    # Like so
      - lazymc.group=mc2
      - lazymc.domain=mc2.example.com
      - lazymc.server_address=mc2:25565
    tty: true
    stdin_open: true
    restart: no
    environment:
      EULA: "TRUE"
    volumes:
      - data-mc2:/data

volumes:
  data-mc1:
  data-mc2:
```
