### ISSUE TITLE
Read MOTD configuration from server.properties file, and hotswap confiurations

### ISSUE THREAD

**Issue by Rubicj** [joesturge/lazymc-docker-proxy#98]
I'd like to set something up to automatically rotate MOTDs. I can change the MOTD of the actual MC server by writing to the server.properties file, but when the server is sleeping/started that's not shown, and instead it shows the contents of the labels, such as `lazymc.motd.sleeping`. 

Is there a good way to update those MOTDs periodically? I plan to have a cronjob running every period (ideally seconds, otherwise minutes) that selects a random message, then applies it to the server.

In case it's relevant, my abbriviated compose file:
```
networks:
  minecraft-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

services:
  lazymc:
    container_name: lazymc
    image: ghcr.io/joesturge/lazymc-docker-proxy:latest
    networks:
      minecraft-network:
        ipv4_address: 172.20.0.2
    environment:
      RUST_LOG: DEBUG
    restart: unless-stopped
    volumes:
      - /mnt/cache/appdata/minecraft/data:/server/mc:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - "25565:25565"
  minecraft:
    image: itzg/minecraft-server:java17
    tty: true
    stdin_open: true
    container_name: minecraft
    networks:
      minecraft-network:
        ipv4_address: 172.20.0.3
    environment:
      VERSION: 1.19.2
      EULA: true
      TYPE: CURSEFORGE
      CF_SERVER_MOD: a modpack
      MEMORY: 16G
      ENABLE_WHITELIST: true
      DISABLE_HEALTHCHECK: true
      DIFFICULTY: normal
    volumes:
      - /mnt/cache/appdata/minecraft/data:/data
      - /mnt/cache/appdata/minecraft/appdata:/appdata
      - /mnt/cache/appdata/minecraft/modpacks:/modpacks:ro
    restart: no
    labels:
      - lazymc.enabled=true
      - lazymc.group=mc
      - lazymc.server.address=172.20.0.3:25565
      - lazymc.public.version=1.19.2
      - lazymc.time.sleep_after=300
      - lazymc.time.minimum_online_time=600
      - lazymc.server.directory=/server/mc
```

If my minecraft container is stopped, and I recreate the image with different `lazymc.motd.sleeping` labels, the new labels aren't pulled in unless I restart the `lazymc` container. That's not a complete dealbreaker, as lazymc does restart very quickly, but if if the container takes 5s to restart and I do this once a minute, that means there's a one-in-twelve chance that when someone tries to connect, lazymc will be restarting. Additionally, when a player tries to join, lazymc then can't find the new container to start.
